/* ============================================================
   N8nEngineAdapter — talks to a real n8n REST API per instance
   (plan §4.10, Phase B; reworked for live instances).

   The Cantila control plane owns one n8n container per automation
   instance (provisioned eagerly by the workspace provisioner). This
   adapter reaches into that container via n8n's *internal* REST API
   (`/rest/*`) — the same surface the n8n editor UI uses — because
   the public `/api/v1` API has no node catalog and no manual-run
   endpoint.

   Auth model (verified against n8n 2.25.7 source):
     * `/rest/*` authenticates with the `n8n-auth` session cookie.
     * The adapter signs in via `POST /rest/login`
       `{ emailOrLdapLoginId, password }` and caches the cookie.
     * A FRESH instance has no users at all — login fails — so the
       adapter lazily claims it via `POST /rest/owner/setup`
       `{ email, firstName, lastName, password }` (skipAuth on the
       n8n side), which also issues the cookie. This makes a brand
       new container usable with zero manual onboarding.
     * Legacy mode: when only `apiKey` is configured (global
       `N8N_BASE_URL`/`N8N_API_KEY` registry wiring) the adapter
       falls back to sending `X-N8N-API-KEY`.

   Run model (verified against 2.25.7):
     * `POST /rest/workflows/:id/run` with
       `{ triggerToStartFrom: { name } }` starts a full manual
       execution and returns `{ data: { executionId } }`.
     * n8n can only execute workflows that HAVE a trigger node, so
       `saveWorkflow` injects an `n8n-nodes-base.manualTrigger` when
       the canonical graph carries no trigger — every workflow saved
       through Cantila is therefore runnable.

   This adapter speaks the *Cantila canonical* `WorkflowGraph` shape
   in and out — the n8n-specific JSON only lives inside the adapter,
   round-tripped on load/save through `cantilaToN8n` /
   `n8nToCantila`. The canvas reads and writes the canonical shape,
   so swapping engines is one adapter swap with no Console code
   change.
   ============================================================ */

import { randomUUID } from "node:crypto";
import type { AutomationKind } from "../../domain/types";
import { id as mkId, now } from "../../lib/ids";
import type {
  AutomationEngineAdapter,
  BindConnectionContext,
  BindConnectionResult,
  ExecutionEvent,
  ExecutionState,
  GraphNode,
  GraphEdge,
  GraphTrigger,
  NodeTypeDescriptor,
  TriggerKind,
  WorkflowGraph,
  WorkflowSummary,
} from "../engine";

export interface N8nEngineConfig {
  baseUrl: string;
  /** Owner-account credentials for cookie-session auth — the primary
   *  auth path for per-instance adapters. */
  email?: string;
  password?: string;
  /** Legacy fallback: sent as `X-N8N-API-KEY` when no email/password
   *  is configured (only meaningful against `/api/v1`-style setups). */
  apiKey?: string;
  /** Optional override for the timeout on individual REST calls. */
  timeoutMs?: number;
}

export const MANUAL_TRIGGER_TYPE = "n8n-nodes-base.manualTrigger";
export const MANUAL_TRIGGER_NAME = "Manual Trigger";

/* ---------- n8n wire types (just the shapes we read/write) ----- */

interface N8nNodeRow {
  /** n8n's internal stable node id (uuid). Generated by the adapter
   *  when missing — execution bookkeeping keys off it. */
  id?: string;
  name: string;
  type: string;
  typeVersion?: number;
  position: [number, number];
  parameters: Record<string, unknown>;
  /** n8n keys credentials by display name; we set the cantila connection
   *  id here so the run hook can look up the bound credential. */
  credentials?: Record<string, { id: string; name: string }>;
}

interface N8nWorkflowRow {
  id?: string;
  name: string;
  nodes: N8nNodeRow[];
  connections: Record<
    string,
    {
      main?: { node: string; type?: string; index?: number }[][];
    }
  >;
  active?: boolean;
  settings?: Record<string, unknown>;
  meta?: Record<string, unknown>;
}

interface N8nExecutionRow {
  id: string;
  workflowId: string;
  status: "new" | "running" | "success" | "error" | "canceled" | "waiting";
  startedAt: string;
  stoppedAt?: string;
  /** n8n stores execution data flattened — over the wire it arrives
   *  either as a nested object or as a JSON string. */
  data?:
    | string
    | {
        resultData?: {
          runData?: Record<
            string,
            {
              executionStatus?: "success" | "error" | "running";
            }[]
          >;
          error?: { message: string };
        };
      };
}

/** Shape of one entry in n8n's `/types/nodes.json` catalog. */
interface N8nNodeDescription {
  name: string;
  displayName: string;
  description?: string;
  group?: string[];
  iconUrl?: string | Record<string, string>;
  icon?: string;
  properties?: unknown[];
  credentials?: { name: string; required?: boolean }[];
}

/* ---------- adapter ---- */

export class N8nEngineAdapter implements AutomationEngineAdapter {
  readonly kind: AutomationKind = "n8n";
  private readonly config: N8nEngineConfig;
  /** Cached `n8n-auth=...` cookie pair; refreshed on 401. */
  private sessionCookie: string | null = null;

  constructor(config: N8nEngineConfig) {
    this.config = {
      timeoutMs: 15_000,
      ...config,
    };
  }

  /* ----- catalog ----- */

  async listNodeTypes(): Promise<NodeTypeDescriptor[]> {
    // n8n's full node catalog is served at `/types/nodes.json` (the
    // editor loads the same file). Entries carry `credentials` rather
    // than the old `credentialsDescription`.
    const raw = await this.fetch<N8nNodeDescription[]>("/types/nodes.json");
    const list = Array.isArray(raw) ? raw : [];
    return list.map((n) => {
      const credentials = n.credentials ?? [];
      const category =
        Array.isArray(n.group) && n.group.length > 0
          ? toTitle(n.group[0])
          : "Core";
      const iconUrl =
        typeof n.iconUrl === "string"
          ? n.iconUrl
          : typeof n.iconUrl === "object" && n.iconUrl !== null
            ? Object.values(n.iconUrl)[0]
            : undefined;
      return {
        id: `n8n:${n.name}`,
        kind: "n8n" as AutomationKind,
        name: n.displayName,
        category,
        blurb: n.description ?? n.displayName,
        glyph: iconUrl ?? n.icon ?? "•",
        // n8n's `properties` array is a JSON-schema-ish parameter spec.
        // We pass it through opaquely so the Console parameter form
        // can render it.
        parameters: { type: "object", properties: n.properties ?? [] },
        requiresConnection: credentials.length > 0,
        connectionProviders: credentials.map((c) => c.name),
      };
    });
  }

  async getNodeType(id: string): Promise<NodeTypeDescriptor | null> {
    const all = await this.listNodeTypes();
    return all.find((n) => n.id === id) ?? null;
  }

  /* ----- workflows ----- */

  async listWorkflows(_instanceId: string): Promise<WorkflowSummary[]> {
    // `GET /rest/workflows` responds `{ count, data: [...] }`.
    const raw = await this.fetch<{ count?: number; data: N8nWorkflowRow[] }>(
      "/rest/workflows",
    );
    return (raw?.data ?? []).map((w) => ({
      id: w.id ?? "",
      name: w.name,
      active: w.active ?? false,
    }));
  }

  async loadWorkflow(
    _instanceId: string,
    workflowId: string,
  ): Promise<WorkflowGraph> {
    const raw = await this.fetch<{ data: N8nWorkflowRow }>(
      `/rest/workflows/${encodeURIComponent(workflowId)}`,
    );
    return n8nToCantila(raw.data);
  }

  async saveWorkflow(
    _instanceId: string,
    graph: WorkflowGraph,
  ): Promise<WorkflowGraph> {
    const body = cantilaToN8n(graph);
    ensureRunnable(body);
    const existing = graph.id && graph.id.length > 0;
    const raw = await this.fetch<{ data: N8nWorkflowRow }>(
      existing ? `/rest/workflows/${encodeURIComponent(graph.id)}` : "/rest/workflows",
      {
        method: existing ? "PATCH" : "POST",
        body: JSON.stringify(body),
      },
    );
    return n8nToCantila(raw.data);
  }

  async deleteWorkflow(
    _instanceId: string,
    workflowId: string,
  ): Promise<boolean> {
    const res = await this.fetchRaw(
      `/rest/workflows/${encodeURIComponent(workflowId)}`,
      { method: "DELETE" },
    );
    return res.ok;
  }

  /* ----- execution ----- */

  async runWorkflow(
    _instanceId: string,
    workflowId: string,
    _input?: unknown,
  ): Promise<{ executionId: string }> {
    // n8n executes the stored workflow (it reloads it from its own DB)
    // starting from a named trigger node. Find one — preferring the
    // manual trigger, which never waits on an external webhook.
    const wf = await this.fetch<{ data: N8nWorkflowRow }>(
      `/rest/workflows/${encodeURIComponent(workflowId)}`,
    );
    const triggerName = pickTriggerNode(wf.data?.nodes ?? []);
    if (!triggerName) {
      throw new Error(
        "workflow has no trigger node — add a Manual Trigger (or re-save it through Cantila, which adds one automatically)",
      );
    }
    const raw = await this.fetch<{
      data: { executionId?: string; waitingForWebhook?: boolean };
    }>(`/rest/workflows/${encodeURIComponent(workflowId)}/run`, {
      method: "POST",
      body: JSON.stringify({ triggerToStartFrom: { name: triggerName } }),
    });
    if (!raw?.data?.executionId) {
      if (raw?.data?.waitingForWebhook) {
        throw new Error(
          "workflow is waiting for its webhook trigger — call the webhook URL to start it",
        );
      }
      throw new Error("n8n did not return an execution id");
    }
    return { executionId: String(raw.data.executionId) };
  }

  async getExecution(
    _instanceId: string,
    executionId: string,
  ): Promise<ExecutionState | null> {
    let raw: { data?: N8nExecutionRow } | null = null;
    try {
      raw = await this.fetch<{ data: N8nExecutionRow }>(
        `/rest/executions/${encodeURIComponent(executionId)}`,
      );
    } catch {
      return null;
    }
    if (!raw?.data) return null;
    return n8nExecToCantila(raw.data);
  }

  async *streamExecution(
    instanceId: string,
    executionId: string,
  ): AsyncIterable<ExecutionEvent> {
    // n8n's push channel is a websocket; for HTTP we poll the execution
    // row until it terminates and emit synthesised events per node so
    // the Console feed feels live regardless of transport.
    yield { at: now(), executionId, kind: "execution_started" };
    const emitted = new Set<string>();
    for (let attempt = 0; attempt < 300; attempt += 1) {
      const exec = await this.getExecution(instanceId, executionId);
      if (!exec) {
        yield {
          at: now(),
          executionId,
          kind: "execution_finished",
          detail: "execution not found",
        };
        return;
      }
      for (const [nodeId, state] of Object.entries(exec.nodeStates)) {
        const tag = `${nodeId}:${state}`;
        if (emitted.has(tag)) continue;
        emitted.add(tag);
        if (state === "running") {
          yield { at: now(), executionId, nodeId, kind: "node_started" };
        } else if (state === "success") {
          yield { at: now(), executionId, nodeId, kind: "node_succeeded" };
        } else if (state === "failed") {
          yield { at: now(), executionId, nodeId, kind: "node_failed" };
        }
      }
      if (exec.status === "success" || exec.status === "failed") {
        yield {
          at: now(),
          executionId,
          kind: "execution_finished",
          detail: exec.error,
        };
        return;
      }
      await sleep(1000);
    }
    // Time-out fallback so the iterator can't hang forever.
    yield {
      at: now(),
      executionId,
      kind: "execution_finished",
      detail: "stream timed out after 5 min",
    };
  }

  /* ----- credentials ----- */

  async bindConnection(
    _instanceId: string,
    connectionId: string,
    ctx?: BindConnectionContext,
  ): Promise<BindConnectionResult> {
    const expiresAt = new Date(Date.now() + 5 * 60 * 1000).toISOString();
    if (!ctx) {
      // Phase B fallback — no resolved payload, so we mint a placeholder.
      // The Cantila broker layer (`cp.bindConnectionForRun`) always
      // supplies ctx today; this branch survives for callers that hand
      // a connectionId in without going through the broker.
      const engineCredentialId = `n8n:${connectionId}:${mkId("ecred")}`;
      return { engineCredentialId, expiresAt, pushed: false };
    }
    const credentialType = mapProviderToN8nCredentialType(ctx.provider);
    if (!credentialType) {
      // Unknown provider — n8n won't know what credential schema to
      // store. Drop back to the placeholder so the run can still
      // reference an id; the audit log records `pushed: false` so the
      // operator can see the gap and extend the mapping table.
      const engineCredentialId = `n8n:${connectionId}:${mkId("ecred")}`;
      return { engineCredentialId, expiresAt, pushed: false };
    }
    const data = mapPayloadToN8nCredentialData(ctx.provider, ctx.payload);
    const body = JSON.stringify({
      name: ctx.name ?? `cantila-${connectionId}`,
      type: credentialType,
      data,
    });
    try {
      const res = await this.fetch<{ data: { id: string | number } }>(
        "/rest/credentials",
        { method: "POST", body },
      );
      const engineCredentialId =
        res?.data?.id !== undefined ? String(res.data.id) : `n8n:${connectionId}:${mkId("ecred")}`;
      return { engineCredentialId, expiresAt, pushed: true };
    } catch {
      // n8n rejected the push (auth, schema mismatch, network). Fall
      // through to the placeholder so the run still gets an id; the
      // audit row records `pushed: false` and the operator sees why.
      const engineCredentialId = `n8n:${connectionId}:${mkId("ecred")}`;
      return { engineCredentialId, expiresAt, pushed: false };
    }
  }

  async unbindConnection(
    _instanceId: string,
    engineCredentialId: string,
  ): Promise<void> {
    // Placeholder ids carry the `n8n:` prefix; only engine-side ids
    // (numeric or cuid strings n8n hands back) round-trip to a DELETE.
    if (engineCredentialId.startsWith("n8n:")) return;
    try {
      await this.fetchRaw(
        `/rest/credentials/${encodeURIComponent(engineCredentialId)}`,
        { method: "DELETE" },
      );
    } catch {
      // Idempotent — n8n may have already TTL'd or been rebooted.
    }
  }

  /* ----- session management ----- */

  /** Sign in (or claim a fresh instance) and cache the session cookie.
   *  Exposed for tests; callers normally never invoke it directly. */
  async ensureSession(force = false): Promise<string | null> {
    const { email, password } = this.config;
    if (!email || !password) return null; // legacy api-key mode
    if (this.sessionCookie && !force) return this.sessionCookie;

    // 1. Normal login.
    const login = await this.rawRequest("/rest/login", {
      method: "POST",
      body: JSON.stringify({ emailOrLdapLoginId: email, password }),
    });
    if (login.ok) {
      this.sessionCookie = extractAuthCookie(login) ?? this.sessionCookie;
      if (this.sessionCookie) return this.sessionCookie;
    }

    // 2. Fresh instance — no owner yet. Claim it (skipAuth endpoint;
    //    fails harmlessly with 4xx when an owner already exists).
    const setup = await this.rawRequest("/rest/owner/setup", {
      method: "POST",
      body: JSON.stringify({
        email,
        firstName: "Cantila",
        lastName: "Admin",
        password,
      }),
    });
    if (setup.ok) {
      this.sessionCookie = extractAuthCookie(setup) ?? this.sessionCookie;
      if (this.sessionCookie) return this.sessionCookie;
    }

    const detail = login.ok ? "no auth cookie issued" : `login ${login.status}, setup ${setup.status}`;
    throw new Error(`n8n sign-in failed: ${detail}`);
  }

  /* ----- HTTP plumbing ----- */

  private async fetch<T>(
    path: string,
    init: RequestInit = {},
  ): Promise<T> {
    const res = await this.fetchRaw(path, init);
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error(
        `n8n ${init.method ?? "GET"} ${path} failed: ${res.status} ${text.slice(0, 300)}`,
      );
    }
    const ct = res.headers.get("content-type") ?? "";
    if (!ct.includes("json")) {
      return undefined as unknown as T;
    }
    return (await res.json()) as T;
  }

  private async fetchRaw(
    path: string,
    init: RequestInit = {},
  ): Promise<Response> {
    await this.ensureSession().catch((err) => {
      // Surface sign-in failures with their own message rather than a
      // generic 401 from the endpoint we were about to call.
      throw err instanceof Error ? err : new Error(String(err));
    });
    let res = await this.rawRequest(path, init);
    // Session may have expired (container restart) — retry once with a
    // forced re-login.
    if (res.status === 401 && this.config.email && this.config.password) {
      this.sessionCookie = null;
      await this.ensureSession(true);
      res = await this.rawRequest(path, init);
    }
    return res;
  }

  /** Lowest-level request: applies base URL, headers, cookie, timeout —
   *  but no session bootstrapping (used BY the session bootstrapper). */
  private async rawRequest(
    path: string,
    init: RequestInit = {},
  ): Promise<Response> {
    const url = `${this.config.baseUrl.replace(/\/$/, "")}${path}`;
    const headers: Record<string, string> = {
      accept: "application/json",
      ...((init.headers ?? {}) as Record<string, string>),
    };
    if (this.config.apiKey) headers["X-N8N-API-KEY"] = this.config.apiKey;
    if (this.sessionCookie) headers.cookie = this.sessionCookie;
    if (init.body && !headers["content-type"]) {
      headers["content-type"] = "application/json";
    }
    const ctl = new AbortController();
    const timer = setTimeout(
      () => ctl.abort(),
      this.config.timeoutMs ?? 15_000,
    );
    try {
      return await fetch(url, { ...init, headers, signal: ctl.signal });
    } finally {
      clearTimeout(timer);
    }
  }
}

/* ---------- import: n8n "Download" JSON → canonical graph ----- */

/** Convert a raw n8n workflow export (the JSON you get from n8n's
 *  *Download* / *Copy to clipboard*) into Cantila's canonical
 *  `WorkflowGraph`. Reuses the same `n8nToCantila` translation the live
 *  adapter uses on load, so an imported workflow is indistinguishable
 *  from one authored on the canvas.
 *
 *  The incoming `id` is intentionally dropped — import always creates a
 *  *new* workflow, so the returned graph carries `id: ""` and the engine
 *  assigns a fresh id on save. Throws a descriptive `Error` on input that
 *  isn't a workflow export (so the route can return a clean 400). */
export function parseN8nWorkflowExport(input: unknown): WorkflowGraph {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    throw new Error("invalid workflow export: expected a JSON object");
  }
  const obj = input as Record<string, unknown>;
  if (!Array.isArray(obj.nodes)) {
    throw new Error("invalid workflow export: `nodes` array is required");
  }
  const row: N8nWorkflowRow = {
    // Drop `id` — import mints a fresh workflow.
    name: typeof obj.name === "string" && obj.name ? obj.name : "Imported workflow",
    nodes: obj.nodes as N8nWorkflowRow["nodes"],
    connections: (obj.connections as N8nWorkflowRow["connections"]) ?? {},
    meta: (obj.meta as Record<string, unknown> | undefined),
  };
  const graph = n8nToCantila(row);
  return { ...graph, id: "" };
}

/* ---------- canonical-graph ↔ n8n translation ----- */

function n8nToCantila(row: N8nWorkflowRow): WorkflowGraph {
  const nodes: GraphNode[] = row.nodes.map((n, i) => ({
    id: n.name || `node_${i}`,
    type: `n8n:${n.type}`,
    position: { x: n.position?.[0] ?? 0, y: n.position?.[1] ?? 0 },
    parameters: n.parameters ?? {},
    connectionId: pickConnectionId(n.credentials),
  }));

  const edges: GraphEdge[] = [];
  for (const [fromName, conn] of Object.entries(row.connections ?? {})) {
    const ports = conn.main ?? [];
    for (let portIdx = 0; portIdx < ports.length; portIdx += 1) {
      for (const target of ports[portIdx]) {
        edges.push({
          id: `${fromName}->${target.node}#${portIdx}`,
          fromNodeId: fromName,
          toNodeId: target.node,
          fromPort: portIdx === 0 ? undefined : `main:${portIdx}`,
        });
      }
    }
  }

  const triggers: GraphTrigger[] = [];
  for (const n of nodes) {
    const kind = classifyTrigger(n.type);
    if (kind) triggers.push({ id: `trg_${n.id}`, kind, config: n.parameters });
  }

  return {
    id: row.id ?? "",
    name: row.name,
    nodes,
    edges,
    triggers,
    meta: row.meta,
  };
}

export function cantilaToN8n(graph: WorkflowGraph): N8nWorkflowRow {
  const nodes: N8nNodeRow[] = graph.nodes.map((n) => ({
    // n8n requires a stable per-node uuid alongside the display name.
    id: randomUUID(),
    name: n.id,
    // n8n's wire type strips the `n8n:` prefix; we mirror.
    type: n.type.startsWith("n8n:") ? n.type.slice(4) : n.type,
    typeVersion: 1,
    position: [n.position.x, n.position.y],
    parameters: n.parameters,
    credentials: n.connectionId
      ? { default: { id: n.connectionId, name: n.connectionId } }
      : undefined,
  }));

  const connections: N8nWorkflowRow["connections"] = {};
  for (const e of graph.edges) {
    const port = e.fromPort?.startsWith("main:")
      ? Number(e.fromPort.slice(5))
      : 0;
    const fromBucket = (connections[e.fromNodeId] ??= { main: [] });
    const mains = (fromBucket.main ??= []);
    while (mains.length <= port) mains.push([]);
    mains[port].push({ node: e.toNodeId, type: "main", index: 0 });
  }

  return {
    id: graph.id || undefined,
    name: graph.name,
    nodes,
    connections,
    active: false,
    settings: { executionOrder: "v1" },
    meta: graph.meta,
  };
}

/** n8n refuses to execute a workflow with no trigger node. Inject a
 *  manual trigger (wired to the first root node, if any) so everything
 *  saved through Cantila is runnable from the Console. Mutates `row`. */
export function ensureRunnable(row: N8nWorkflowRow): void {
  const hasTrigger = row.nodes.some((n) => classifyTrigger(`n8n:${n.type}`));
  if (hasTrigger) return;

  const minX = row.nodes.length
    ? Math.min(...row.nodes.map((n) => n.position?.[0] ?? 0))
    : 0;
  const minY = row.nodes.length
    ? Math.min(...row.nodes.map((n) => n.position?.[1] ?? 0))
    : 0;
  row.nodes.unshift({
    id: randomUUID(),
    name: MANUAL_TRIGGER_NAME,
    type: MANUAL_TRIGGER_TYPE,
    typeVersion: 1,
    position: [minX - 220, minY],
    parameters: {},
  });

  // Wire the trigger into the graph's roots so a run flows through the
  // existing nodes (n8n executes connected components from the trigger).
  const hasIncoming = new Set<string>();
  for (const conn of Object.values(row.connections ?? {})) {
    for (const port of conn.main ?? []) {
      for (const target of port) hasIncoming.add(target.node);
    }
  }
  const roots = row.nodes
    .filter((n) => n.name !== MANUAL_TRIGGER_NAME && !hasIncoming.has(n.name))
    .map((n) => n.name);
  if (roots.length > 0) {
    row.connections[MANUAL_TRIGGER_NAME] = {
      main: [roots.map((node) => ({ node, type: "main", index: 0 }))],
    };
  }
}

/** Choose the node to start a manual run from. Prefers the manual
 *  trigger; falls back to schedule, then any other trigger-ish node. */
export function pickTriggerNode(nodes: N8nNodeRow[]): string | null {
  const triggers = nodes.filter((n) => classifyTrigger(`n8n:${n.type}`));
  if (triggers.length === 0) return null;
  const manual = triggers.find((n) =>
    n.type.toLowerCase().includes("manualtrigger"),
  );
  if (manual) return manual.name;
  const schedule = triggers.find((n) => {
    const t = n.type.toLowerCase();
    return t.includes("schedule") || t.includes("cron") || t.includes("interval");
  });
  if (schedule) return schedule.name;
  return triggers[0].name;
}

function n8nExecToCantila(row: N8nExecutionRow): ExecutionState {
  const nodeStates: ExecutionState["nodeStates"] = {};
  let dataObj: Exclude<N8nExecutionRow["data"], string> | undefined;
  if (typeof row.data === "string") {
    try {
      dataObj = JSON.parse(row.data) as Exclude<N8nExecutionRow["data"], string>;
    } catch {
      dataObj = undefined;
    }
  } else {
    dataObj = row.data;
  }
  const runData = dataObj?.resultData?.runData ?? {};
  for (const [nodeId, runs] of Object.entries(runData)) {
    const last = Array.isArray(runs) ? runs[runs.length - 1] : undefined;
    const status = last?.executionStatus;
    if (status === "success") nodeStates[nodeId] = "success";
    else if (status === "error") nodeStates[nodeId] = "failed";
    else nodeStates[nodeId] = "running";
  }
  let cantilaStatus: ExecutionState["status"];
  if (row.status === "success") cantilaStatus = "success";
  else if (row.status === "error" || row.status === "canceled")
    cantilaStatus = "failed";
  else if (row.status === "new") cantilaStatus = "queued";
  else cantilaStatus = "running";
  return {
    id: row.id,
    workflowId: row.workflowId,
    status: cantilaStatus,
    startedAt: row.startedAt,
    finishedAt: row.stoppedAt,
    nodeStates,
    error: dataObj?.resultData?.error?.message,
  };
}

/* ---------- helpers ----- */

/** Pull the `n8n-auth` cookie out of a login / owner-setup response. */
function extractAuthCookie(res: Response): string | null {
  const cookies =
    typeof (res.headers as Headers & { getSetCookie?: () => string[] })
      .getSetCookie === "function"
      ? (res.headers as Headers & { getSetCookie: () => string[] }).getSetCookie()
      : res.headers.get("set-cookie")
        ? [res.headers.get("set-cookie") as string]
        : [];
  for (const c of cookies) {
    const m = /(?:^|,\s*)(n8n-auth=[^;]+)/.exec(c);
    if (m) return m[1];
  }
  return null;
}

/** Classify a canonical node type (`n8n:<n8nType>`) as a trigger kind, or
 *  null when it isn't a trigger. Tolerant of both stub-style type ids
 *  (`n8n:webhook`, `n8n:schedule`) and real n8n type names
 *  (`n8n-nodes-base.webhook`, `…manualTrigger`, `…scheduleTrigger`,
 *  legacy `…cron` / `…interval`). */
function classifyTrigger(type: string): TriggerKind | null {
  const t = type.toLowerCase();
  if (t.includes("webhook")) return "webhook";
  if (t.includes("schedule") || t.includes("cron") || t.includes("interval"))
    return "schedule";
  if (t.includes("manualtrigger") || t.endsWith(":manual")) return "manual";
  return null;
}

function pickConnectionId(
  credentials?: Record<string, { id: string; name: string }>,
): string | undefined {
  if (!credentials) return undefined;
  const first = Object.values(credentials)[0];
  return first?.id;
}

function toTitle(s: string): string {
  if (!s) return "Core";
  return s[0].toUpperCase() + s.slice(1);
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

/* ---------- Cantila provider → n8n credential type mapping ----- */

/** Map a Cantila provider id (matches the `ProviderDescriptor.id` in
 *  `connections/providers.ts`) to the n8n credential type name n8n
 *  expects on `POST /rest/credentials`. Returning `null` means "n8n
 *  doesn't model this credential in a shape we can populate" — the
 *  caller falls back to a placeholder id and the audit row records
 *  `pushed: false`. The mapping table is intentionally minimal — every
 *  entry has been spot-checked against n8n's credential schema docs. */
function mapProviderToN8nCredentialType(provider: string): string | null {
  switch (provider) {
    case "openai":
      return "openAiApi";
    case "anthropic":
      return "anthropicApi";
    case "slack":
      return "slackOAuth2Api";
    case "gmail":
      return "gmailOAuth2";
    case "notion":
      return "notionApi";
    case "github":
      return "githubOAuth2Api";
    case "airtable":
      return "airtableTokenApi";
    case "sendgrid":
      return "sendGridApi";
    case "twilio":
      return "twilioApi";
    case "postgres":
      return "postgres";
    case "mysql":
      return "mySql";
    case "http_basic":
      return "httpBasicAuth";
    case "stripe":
      return "stripeApi";
    case "generic_api_key":
      return "httpHeaderAuth";
    default:
      return null;
  }
}

/** Translate the Cantila secret payload into n8n's credential `data`
 *  bag. The key names differ per credential type — n8n's `apiKey` vs
 *  our `api_key`, n8n's `accessToken` vs our `access_token`, etc. We
 *  do the minimum dance per provider so the most common field set
 *  lands correctly; n8n ignores unknown keys in the data object. */
function mapPayloadToN8nCredentialData(
  provider: string,
  payload: Record<string, string>,
): Record<string, string> {
  const accessToken = payload.access_token;
  const refreshToken = payload.refresh_token;
  switch (provider) {
    case "openai":
    case "anthropic":
    case "sendgrid":
    case "stripe":
      return { apiKey: payload.api_key ?? "" };
    case "notion":
      return { apiKey: payload.api_key ?? accessToken ?? "" };
    case "airtable":
      return {
        accessToken: accessToken ?? payload.api_key ?? "",
        ...(refreshToken ? { refreshToken } : {}),
      };
    case "gmail":
    case "slack":
    case "github":
      return {
        accessToken: accessToken ?? "",
        ...(refreshToken ? { refreshToken } : {}),
      };
    case "twilio":
      return {
        accountSid: payload.account_sid ?? "",
        authToken: payload.auth_token ?? "",
      };
    case "postgres":
    case "mysql":
      return { connectionString: payload.connection_string ?? "" };
    case "http_basic":
      return {
        user: payload.username ?? "",
        password: payload.password ?? "",
      };
    case "generic_api_key":
      return {
        name: payload.header_name ?? "Authorization",
        value: payload.api_key ?? "",
      };
    default:
      // Pass through unchanged — better than dropping bytes silently.
      return { ...payload };
  }
}
