/* Port AgentFleet agent markdown into a committed TS roster.
   Usage: node scripts/port-fleet.mjs [agentsDir]
   Default: $FLEET_AGENTS_DIR or <repoRoot>/../AgentFleet/.claude/agents */
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const agentsDir = process.argv[2]
  ? path.resolve(process.argv[2])
  : process.env.FLEET_AGENTS_DIR
  ? path.resolve(process.env.FLEET_AGENTS_DIR)
  : path.resolve(repoRoot, "..", "AgentFleet", ".claude", "agents");

async function walk(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const abs = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(abs)));
    else if (e.name.endsWith(".md")) out.push(abs);
  }
  return out;
}
function parseFrontMatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { meta: {}, body: text.trim() };
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const i = line.indexOf(":");
    if (i === -1) continue;
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { meta, body: m[2].trim() };
}
function divisionFromPath(absPath) {
  const rel = path.relative(agentsDir, absPath).split(path.sep);
  return rel.length > 1 ? rel[0] : "governance";
}
const files = (await walk(agentsDir)).sort();
const roles = [];
for (const f of files) {
  const { meta, body } = parseFrontMatter(await readFile(f, "utf8"));
  const id = meta.name || path.basename(f, ".md");
  roles.push({
    id,
    name: id,
    division: divisionFromPath(f),
    description: meta.description || "",
    model: meta.model === "opus" ? "opus" : "sonnet",
    tools: (meta.tools || "").split(",").map((s) => s.trim()).filter(Boolean),
    systemPrompt: body,
  });
}
const header = `// AUTO-GENERATED by scripts/port-fleet.mjs — do not edit by hand.
// Source: AgentFleet/.claude/agents (${roles.length} agents).
import type { AgentRoleRaw } from "./types";

export const ROSTER: AgentRoleRaw[] = ${JSON.stringify(roles, null, 2)};
`;
const outPath = path.resolve(repoRoot, "src", "fleet", "roster", "roster.generated.ts");
await writeFile(outPath, header, "utf8");
console.log(`Wrote ${roles.length} agents to ${path.relative(repoRoot, outPath)}`);
